SOURCES = [
    {
        "name": "Wall Street Journal",
        "short": "WSJ",
        "url": "https://www.wsj.com/real-estate/commercial-real-estate",
        "method": "scrape",
        "tier_weight": 30,
        "color": "#1a2744",
    },
    {
        "name": "CoStar",
        "short": "CoStar",
        "url": "https://www.costar.com/news",
        "method": "scrape",
        "tier_weight": 30,
        "color": "#1a2744",
    },
    {
        "name": "Green Street",
        "short": "Green St",
        "url": "https://www.greenstreetnews.com/articles",
        "method": "scrape",
        "tier_weight": 28,
        "color": "#1a2744",
    },
    {
        "name": "GlobeStreet",
        "short": "GlobeSt",
        "url": "https://www.globest.com/rss/",
        "method": "rss",
        "tier_weight": 20,
        "color": "#0a6b6b",
    },
    {
        "name": "Commercial Observer",
        "short": "Comm Obs",
        "url": "https://commercialobserver.com/feed/",
        "method": "rss",
        "tier_weight": 20,
        "color": "#0a6b6b",
    },
    {
        "name": "Bisnow",
        "short": "Bisnow",
        "url": "https://www.bisnow.com/rss",
        "method": "rss",
        "tier_weight": 18,
        "color": "#0a6b6b",
    },
    {
        "name": "The Real Deal",
        "short": "Real Deal",
        "url": "https://therealdeal.com/feed/",
        "method": "rss",
        "tier_weight": 18,
        "color": "#0a6b6b",
    },
    {
        "name": "PERE",
        "short": "PERE",
        "url": "https://www.perenews.com/",
        "method": "scrape",
        "tier_weight": 16,
        "color": "#0a6b6b",
    },
    {
        "name": "Connect CRE",
        "short": "ConnectCRE",
        "url": "https://www.connectcre.com/feed/",
        "method": "rss",
        "tier_weight": 10,
        "color": "#555555",
    },
    {
        "name": "NMHC",
        "short": "NMHC",
        "url": "https://www.nmhc.org/news/",
        "method": "scrape",
        "tier_weight": 10,
        "color": "#555555",
    },
    {
        "name": "Nareit",
        "short": "Nareit",
        "url": "https://www.reit.com/news/rss.xml",
        "method": "rss",
        "tier_weight": 10,
        "color": "#555555",
    },
]

MAX_ARTICLES_PER_SOURCE = 5
MAX_TOTAL_ARTICLES = 25
SUMMARY_MAX_CHARS = 280
